# Generated by Django 4.0.3 on 2022-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting confirmation', 'waiting confirmation'), ('ordered', 'ordered'), ('shipped', 'shipped'), ('received', 'received')], default='waiting confirmation', max_length=255),
        ),
    ]
