# Generated by Django 4.0.3 on 2022-09-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Authorized', 'Authorized'), ('Awaiting Shipment', 'Awaiting Shipment'), ('Delivering', 'Delivering'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Processing', max_length=255),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
