# Generated by Django 4.0.3 on 2022-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash')], default='cash', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Authorized', 'Authorized'), ('Awaiting Shipment', 'Awaiting Shipment'), ('Delivering', 'Delivering'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Processing', max_length=255),
        ),
    ]
