# Generated by Django 4.0.3 on 2022-08-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
