# Generated by Django 4.0.3 on 2022-08-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_comment_body_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
