# Generated by Django 4.0.3 on 2022-10-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_statistíc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='statistíc',
            new_name='statistics',
        ),
    ]
